// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVNkd57lh3SX-VuWsRaM3gFHhBKSwYmHw',
    appId: '1:716103578847:web:3196429828bd458fb4256a',
    messagingSenderId: '716103578847',
    projectId: 'flutter-meet-up-app',
    authDomain: 'flutter-meet-up-app.firebaseapp.com',
    storageBucket: 'flutter-meet-up-app.appspot.com',
    measurementId: 'G-C7EDF84KPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGC0VlA4IyHF1IzcEjLUUIELAi0s4Yko',
    appId: '1:716103578847:android:c0650b80f016f8b5b4256a',
    messagingSenderId: '716103578847',
    projectId: 'flutter-meet-up-app',
    storageBucket: 'flutter-meet-up-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FV8leXJ_0HA8IvzCg9EoJLJ0osWdDbM',
    appId: '1:716103578847:ios:84f12e791c3a019db4256a',
    messagingSenderId: '716103578847',
    projectId: 'flutter-meet-up-app',
    storageBucket: 'flutter-meet-up-app.appspot.com',
    iosClientId: '716103578847-pjaim0lqshtvgvd1su7inumot860bq6g.apps.googleusercontent.com',
    iosBundleId: 'q',
  );
}
